services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false

  UserAgreementBundle\Controller\:
    resource: '../../Controller/'
  UserAgreementBundle\Repository\:
    resource: '../../Repository/'
  UserAgreementBundle\Service\:
    resource: '../../Service/'
    public: true
  UserAgreementBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
    public: true
  UserAgreementBundle\Procedure\:
    resource: '../../Procedure/'
    public: true
